//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int ID { get; set; }
        public string Title_Note { get; set; }
        public string RichTextNote { get; set; }
        public string User_k { get; set; }
    
        public virtual User User { get; set; }
    }
}
